apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: worker-cluster01
  generateName: baremetal-machine-worker
  namespace: metal3
spec:
  providerSpec:
    value:
      apiVersion: "baremetal.cluster.k8s.io/v1alpha1"
      kind: "BareMetalMachineProviderSpec"
      image:
        url: http://10.212.0.41:30180/images/xenial-server-cloudimg-amd64-disk1.img
        checksum: http://10.212.0.41:30180/images/xenial-server-cloudimg-amd64-disk1.img.md5sum
      userData:
        name: master-user-data
        namespace: metal3
